### ISSUE TITLE
Documentation & Setup

### ISSUE THREAD

**Issue by jadok** [jadok/6me#4]
Improving documentations on each project.
Setting up a default unit testing setup, prettier/eslint, commitlint, documentation on each project.

# TODO
- [ ] README updated on each project
   - [ ] Main
   - [ ] News
   - [ ] form
   - [ ] markdown-utils
- [ ] Unit test setup on each project
   - [ ] News
   - [ ] form
   - [x] markdown-utils
- [ ] Prettier/eslint setup on each project
   - [ ] News
   - [ ] form
   - [x] markdown-utils
